[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py311"]

[tool.ruff]
select = ["E", "F", "W", "I"]
ignore = ["E501"]
fixable = ["ALL"]
target-version = "py311"
