SD_MODELS = [
    "runwayml/stable-diffusion-v1-5",
    "stabilityai/stable-diffusion-2-1",
    "SG161222/Realistic_Vision_V2.0",
    "stabilityai/stable-diffusion-xl-base-1.0",
]

SD_SCHEDULERS = [
    "DPM++ 2M",
    "DPM++ 2M Karras",
    "DPM++ 2M SDE",
    "DPM++ 2M SDE Karras",
    "Euler",
    "Euler A",
]

FOOOCUS_STYLES = [
    "Fooocus V2",
    "Fooocus Enhance",
    "Fooocus Sharp",
    "Fooocus Masterpiece",
    "Fooocus Photograph",
    "Fooocus Negative",
    "Fooocus Cinematic",
    "SAI 3D Model",
    "SAI Analog Film",
    "SAI Anime",
    "SAI Cinematic",
    "SAI Comic Book",
    "SAI Craft Clay",
    "SAI Digital Art",
    "SAI Enhance",
    "SAI Fantasy Art",
    "SAI Isometric",
    "SAI Line Art",
    "SAI Lowpoly",
    "SAI Neonpunk",
    "SAI Origami",
    "SAI Photographic",
    "SAI Pixel Art",
    "SAI Texture",
    "MRE Cinematic Dynamic",
    "MRE Spontaneous Picture",
    "MRE Artistic Vision",
    "MRE Dark Dream",
    "MRE Gloomy Art",
    "MRE Bad Dream",
    "MRE Underground",
    "MRE Surreal Painting",
    "MRE Dynamic Illustration",
    "MRE Undead Art",
    "MRE Elemental Art",
    "MRE Space Art",
    "MRE Ancient Illustration",
    "MRE Brave Art",
    "MRE Heroic Fantasy",
    "MRE Dark Cyberpunk",
    "MRE Lyrical Geometry",
    "MRE Sumi E Symbolic",
    "MRE Sumi E Detailed",
    "MRE Manga",
    "MRE Anime",
    "MRE Comic",
    "Ads Advertising",
    "Ads Automotive",
    "Ads Corporate",
    "Ads Fashion Editorial",
    "Ads Food Photography",
    "Ads Gourmet Food Photography",
    "Ads Luxury",
    "Ads Real Estate",
    "Ads Retail",
    "Artstyle Abstract",
    "Artstyle Abstract Expressionism",
    "Artstyle Art Deco",
    "Artstyle Art Nouveau",
    "Artstyle Constructivist",
    "Artstyle Cubist",
    "Artstyle Expressionist",
    "Artstyle Graffiti",
    "Artstyle Hyperrealism",
    "Artstyle Impressionist",
    "Artstyle Pointillism",
    "Artstyle Pop Art",
    "Artstyle Psychedelic",
    "Artstyle Renaissance",
    "Artstyle Steampunk",
    "Artstyle Surrealist",
    "Artstyle Typography",
    "Artstyle Watercolor",
    "Futuristic Biomechanical",
    "Futuristic Biomechanical Cyberpunk",
    "Futuristic Cybernetic",
    "Futuristic Cybernetic Robot",
    "Futuristic Cyberpunk Cityscape",
    "Futuristic Futuristic",
    "Futuristic Retro Cyberpunk",
    "Futuristic Retro Futurism",
    "Futuristic Sci Fi",
    "Futuristic Vaporwave",
    "Game Bubble Bobble",
    "Game Cyberpunk Game",
    "Game Fighting Game",
    "Game Gta",
    "Game Mario",
    "Game Minecraft",
    "Game Pokemon",
    "Game Retro Arcade",
    "Game Retro Game",
    "Game Rpg Fantasy Game",
    "Game Strategy Game",
    "Game Streetfighter",
    "Game Zelda",
    "Misc Architectural",
    "Misc Disco",
    "Misc Dreamscape",
    "Misc Dystopian",
    "Misc Fairy Tale",
    "Misc Gothic",
    "Misc Grunge",
    "Misc Horror",
    "Misc Kawaii",
    "Misc Lovecraftian",
    "Misc Macabre",
    "Misc Manga",
    "Misc Metropolis",
    "Misc Minimalist",
    "Misc Monochrome",
    "Misc Nautical",
    "Misc Space",
    "Misc Stained Glass",
    "Misc Techwear Fashion",
    "Misc Tribal",
    "Misc Zentangle",
    "Papercraft Collage",
    "Papercraft Flat Papercut",
    "Papercraft Kirigami",
    "Papercraft Paper Mache",
    "Papercraft Paper Quilling",
    "Papercraft Papercut Collage",
    "Papercraft Papercut Shadow Box",
    "Papercraft Stacked Papercut",
    "Papercraft Thick Layered Papercut",
    "Photo Alien",
    "Photo Film Noir",
    "Photo Glamour",
    "Photo Hdr",
    "Photo Iphone Photographic",
    "Photo Long Exposure",
    "Photo Neon Noir",
    "Photo Silhouette",
    "Photo Tilt Shift",
    "Cinematic Diva",
    "Abstract Expressionism",
    "Academia",
    "Action Figure",
    "Adorable 3D Character",
    "Adorable Kawaii",
    "Art Deco",
    "Art Nouveau",
    "Astral Aura",
    "Avant Garde",
    "Baroque",
    "Bauhaus Style Poster",
    "Blueprint Schematic Drawing",
    "Caricature",
    "Cel Shaded Art",
    "Character Design Sheet",
    "Classicism Art",
    "Color Field Painting",
    "Colored Pencil Art",
    "Conceptual Art",
    "Constructivism",
    "Cubism",
    "Dadaism",
    "Dark Fantasy",
    "Dark Moody Atmosphere",
    "Dmt Art Style",
    "Doodle Art",
    "Double Exposure",
    "Dripping Paint Splatter Art",
    "Expressionism",
    "Faded Polaroid Photo",
    "Fauvism",
    "Flat 2d Art",
    "Fortnite Art Style",
    "Futurism",
    "Glitchcore",
    "Glo Fi",
    "Googie Art Style",
    "Graffiti Art",
    "Harlem Renaissance Art",
    "High Fashion",
    "Idyllic",
    "Impressionism",
    "Infographic Drawing",
    "Ink Dripping Drawing",
    "Japanese Ink Drawing",
    "Knolling Photography",
    "Light Cheery Atmosphere",
    "Logo Design",
    "Luxurious Elegance",
    "Macro Photography",
    "Mandola Art",
    "Marker Drawing",
    "Medievalism",
    "Minimalism",
    "Neo Baroque",
    "Neo Byzantine",
    "Neo Futurism",
    "Neo Impressionism",
    "Neo Rococo",
    "Neoclassicism",
    "Op Art",
    "Ornate And Intricate",
    "Pencil Sketch Drawing",
    "Pop Art 2",
    "Rococo",
    "Silhouette Art",
    "Simple Vector Art",
    "Sketchup",
    "Steampunk 2",
    "Surrealism",
    "Suprematism",
    "Terragen",
    "Tranquil Relaxing Atmosphere",
    "Sticker Designs",
    "Vibrant Rim Light",
    "Volumetric Lighting",
    "Watercolor 2",
    "Whimsical And Playful",
    "Mk Chromolithography",
    "Mk Cross Processing Print",
    "Mk Dufaycolor Photograph",
    "Mk Herbarium",
    "Mk Punk Collage",
    "Mk Mosaic",
    "Mk Van Gogh",
    "Mk Coloring Book",
    "Mk Singer Sargent",
    "Mk Pollock",
    "Mk Basquiat",
    "Mk Andy Warhol",
    "Mk Halftone Print",
    "Mk Gond Painting",
    "Mk Albumen Print",
    "Mk Aquatint Print",
    "Mk Anthotype Print",
    "Mk Inuit Carving",
    "Mk Bromoil Print",
    "Mk Calotype Print",
    "Mk Color Sketchnote",
    "Mk Cibulak Porcelain",
    "Mk Alcohol Ink Art",
    "Mk One Line Art",
    "Mk Blacklight Paint",
    "Mk Carnival Glass",
    "Mk Cyanotype Print",
    "Mk Cross Stitching",
    "Mk Encaustic Paint",
    "Mk Embroidery",
    "Mk Gyotaku",
    "Mk Luminogram",
    "Mk Lite Brite Art",
    "Mk Mokume Gane",
    "Pebble Art",
    "Mk Palekh",
    "Mk Suminagashi",
    "Mk Scrimshaw",
    "Mk Shibori",
    "Mk Vitreous Enamel",
    "Mk Ukiyo E",
    "Mk Vintage Airline Poster",
    "Mk Vintage Travel Poster",
    "Mk Bauhaus Style",
    "Mk Afrofuturism",
    "Mk Atompunk",
    "Mk Constructivism",
    "Mk Chicano Art",
    "Mk De Stijl",
    "Mk Dayak Art",
    "Mk Fayum Portrait",
    "Mk Illuminated Manuscript",
    "Mk Kalighat Painting",
    "Mk Madhubani Painting",
    "Mk Pictorialism",
    "Mk Pichwai Painting",
    "Mk Patachitra Painting",
    "Mk Samoan Art Inspired",
    "Mk Tlingit Art",
    "Mk Adnate Style",
    "Mk Ron English Style",
    "Mk Shepard Fairey Style",
]

FOOOCUS_ASPECT_RATIOS = [
    "1024x1024",
    "1024x960",
    "1088x960",
    "1088x896",
    "1152x896",
    "1152x832",
    "1216x832",
    "1280x768",
    "1344x768",
    "1344x704",
    "1408x704",
    "1472x704",
    "1536x640",
    "1600x640",
    "1664x576",
    "1728x576",
    "704x1408",
    "704x1344",
    "768x1344",
    "768x1280",
    "832x1216",
    "832x1152",
    "896x1152",
    "896x1088",
    "960x1088",
    "960x1024",
]
