from typing import Literal

import discord
from discord import app_commands

from fal_bot import utils
from fal_bot.consts import SD_MODELS

LORA_BASE_URL = "https://110602490-lora.gateway.alpha.fal.ai"


@app_commands.command(
    name="diffusion",
    description="Run any stable diffusion model with any loras.",
)
@app_commands.autocomplete(model_name=utils.autocomplete_from(SD_MODELS))
async def command(
    interaction: discord.Interaction,
    prompt: str,
    model_name: str = "stabilityai/stable-diffusion-xl-base-1.0",
    mode: Literal["Speed", "Quality"] = "Speed",
):
    await interaction.response.send_message("Your request has been received.")
    with utils.Timed() as timer:
        result = await utils.submit_interactive_task(
            interaction,
            LORA_BASE_URL,
            model_name=model_name,
            prompt=prompt,
            num_inference_steps=35 if mode == "Speed" else 50,
        )

    embed = utils.make_prompted_image_embed(
        title="Stable Diffusion Image",
        image_url=result["images"][0]["url"],
        prompt=prompt,
        fields={
            "Model": model_name,
            "Mode": mode,
            "Time Taken": f"{timer.elapsed:.2f}s",
            "Generated by": interaction.user.mention,
        },
    )
    await interaction.edit_original_response(content=None, embed=embed)
